# 基础镜像
FROM  eclipse-temurin:21-jre
# author
MAINTAINER spzx

# 挂载目录
VOLUME /home/spzx
# 创建目录
RUN mkdir -p /home/spzx
# 指定路径
WORKDIR /home/spzx
# 复制jar文件到路径
COPY ./jar/spzx-job.jar /home/spzx/spzx-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","spzx-job.jar"]
