# 基础镜像
FROM  eclipse-temurin:21-jre
# author
MAINTAINER spzx

# 挂载目录
VOLUME /home/spzx
# 创建目录
RUN mkdir -p /home/spzx
# 指定路径
WORKDIR /home/spzx
# 复制jar文件到路径
COPY ./jar/spzx-system.jar /home/spzx/spzx-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","spzx-system.jar"]
